#!/bin/sh

echo "==========================================="
echo "          QMath install script             "
echo "==========================================="
echo
OS=$(uname)
if [ $OS == 'QNX' ]; then
 if(test -z "$QRTS") then
  echo " ERROR: Please set the QRTS environment variable before proceeding."
  echo " Follow installation procedure for QRTS software such as BaseQRTS"
  echo " Re-run this script after creating all relevant QRTS directories."
  exit 1
 fi
 INSTDIR=$QRTS
 USER=$(id -un)
else
 INSTDIR='/usr/local'
 USER=$(whoami)
fi
if [ $USER != "root" ]
then
  echo "ERROR: You should be root to run this script."
  exit 1
fi
echo "* Is GSL installed [y/n]?"
read response
if [ $response == 'y' ]; then
 HASGSL='yes'
else
 HASGSL='no'
fi

echo
echo "* Install to $INSTDIR [y/n]?"
read response
if [ $response != 'y' ]; then
 echo "* Specify install directory"
 read INSTDIR
fi

make clean
echo
echo "----- Compiling library -----"
echo
make usegsl=$HASGSL
make install INSTALLDIR=$INSTDIR usegsl=$HASGSL
